name: Branch build

on:
  push: 

  workflow_dispatch:

jobs:
  branch-build:

    runs-on: ubuntu-latest
    #if: github.ref == 'refs/head/main'

    steps:
    - uses: actions/checkout@v1

    # install .NET core version
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    
    - run: cd ./src
    - run: dotnet build --configuration Release ./dotnet-core-webapp/dotnetcore-webapp.csproj
      
    - run: dotnet publish -c Release -o dotnetcorewebapp ./dotnet-core-webapp
