name: Branch build

on:
  push: 

  workflow_dispatch:

jobs:
  branch-build:

    runs-on: ubuntu-latest
    #if: github.ref == 'refs/head/main'
    environment: Demo

    steps:
    - uses: actions/checkout@v3

    # install .NET core version
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    
    - run: dotnet build --configuration Release ./src/dotnet-core-webapp/dotnetcore-webapp.csproj
      
    - name: dotnet publish
      run: |
        cd ./src 
        dotnet publish -c Release -o dotnetcorewebapp ./dotnet-core-webapp

    - name: Upload artefact
      uses: actions/upload-artifact@v2
      with:
        name: webapp
        path: src/dotnet-core-webapp
