name: Branch build

on:
  push: 

  workflow_dispatch:


jobs:
  branch-build:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/head/main'

    steps:
    - uses: actions/checkout@v1

    - name: Hello world
      run: echo 'Hello world!'
    